const authConstants = {
    SET_IS_NEW_USER: "SET_IS_NEW_USER",
    SET_USER: "SET_USER",
    RESET_AUTH_DATA_STATE: "RESET_AUTH_DATA_STATE",
    SET_TAKE_PROFILE_DATA_TRUE: "SET_TAKE_PROFILE_DATA_TRUE",
    SET_TAKE_PROFILE_DATA_FALSE: "SET_TAKE_PROFILE_DATA_FALSE",
}

export default authConstants
